4:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_nl/dist_4/49.pt'
  label: "k=4"

8:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_nl/dist_8/49.pt'
  label: "k=8"

16:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_nl/dist_16/49.pt'
  label: "k=16"

32:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/grid_nl/dist_32/49.pt'
  label: "k=32"