none:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/carla/fiery_evidential/19.pt'
  label: "No regularization"

reg:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/aug/none_.1/19.pt'
  label: "OOD Regularization"

vac:
  config: 'configs/eval_carla_fiery_evidential.yaml'
  path: 'outputs/aug/vac_128/19.pt'
  label: "OOD Regularization + Vacuity"